sudo: required

services:
  - docker

language: bash

env:
  global:
    # DOCKER_USER
    - secure: "Yn+yMjAW8SmnESPlocprCMD/1GO73e+xRmOGYCFlzEQRwrjp3/PdBCaOaAtokz6yk2hb3T5zrCJfD3ASrhhrzjlw0+wcd0PxaPIQJoh2IAG8dbM0khqEzfutMjws/Dah3KAJE8FhVxFGTKA0KJOFmT4WB98XEoe/SCsmDTY9wmZcOyB9oINIUcKEpApq0sz6OqlLl0L27H0UWgCQc51VpoVkUxsOM/jQSAF4/A8YOQ7NC2ZF2iOX+Vz0GZWANFI1cHEPK8D3SELOYrrOx/9AS8uNyevVElw2Z8BTS3xDgTQmgLlbj3enNSXAxzy2II1oEb7zchRsb+Cs7Iw3S6vFMZQHLqc8RI8J8QYZrgeeh3OwG3/j0PyGWuVHyg3p5dXp9f/425O99qYYPpAsT0pNl22nVuwZJmSF1MTKAPOyQvw41+n02wItK6tKycv9db4Apy7uTKf+cXQ9xwnegBGEssCujX2tCj8rWGCou1mB/QSF/X7qVOIeELh/y/wL0+YNPT6/sUKFk9HOFS7GcxEUFqWYDsuq2VhjPQdzRSkdoGCKd5ZqYzBq5NwzrcYhcZBpqiP2edxjB4GJUv+SUMzR57jfaE9JmVD33AFkYNuHxkaqJ1EYduDfgjaTwQaMHARvn3BENZdtZMU96QrOCHwMI7P6wlDkM8jv/J+yJpwdu30="
    # DOCKER_PASS
    - secure: "mRIuppBgk21l/TN0wo962A6XE8OKKUIShV/T7UDIv7o6c3btXZggC2m3LaCxHJphwjLV4VsZJ5lgysyz7mjfiZLxL/6+ncfArXqUwqoeWayTObUGvs6P7mzaSEGs5NjKb4vKBljcpyzAC6cBf603yESxaccHuxU/ZyxIBseyCUx18an1ItTViUfSIlFBiEJ1IB57HXmf0U/IOfF+Hqj8WnvVfQDOZvNjbt+vLjnt8tzeNXDrj9IquI9dQr8MHXq2ZBvBnI3uDJhgU4HWf8hQWNlWcHzQygU/eDZipw8QpkJWdqpLUQJtogcT3bVIZ0qaYAhUop57Ugf/qBvrDlikrgwJGICAZISht5teXYwdjCeQnA5ufL1sG3Q+SPcZqmj78EzCVOUwyvkTJqTLVB3PpEbi20WTpETxfGXGEeOmzn8sQfB0jg+NaLN5yp9v0i5QAinqatZ2dULPrES+8lCsHWoJ9qoTz+xNQWTXzBeTDxn2ncuDe0inNpVEib/tZjN+ANgdNnldynDz+EF7ITVF9dHN5eiavqT7sBMwPiBdttvqWRDpmW+79RuYN8S578OzfXSCl9jiWY9ymLSH2LlM5WRp8rN2bb3z4nNoGzUkO0tiIHp9svXPPJ0xztZshJrxqfM+t1ZMiiiOZUtWHX1AjgcxlY8UmH+PEJqX1JIpNX8="

script:
  - travis_wait 30 git submodule update --init
  - curl -O -L https://github.com/grammarly/rocker/releases/download/1.3.0/rocker_linux_amd64.tar.gz
  - tar xvf rocker_linux_amd64.tar.gz
  - cd code/
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then ../rocker build; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then ../rocker build --auth $DOCKER_USER:$DOCKER_PASS --push; fi'